name: base_core
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.9.2
  rxdart: 0.26.0
  logging: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
